use_frameworks!

target 'PlagiarismChecker_Example' do
  pod 'PlagiarismChecker', :git => 'git@github.com:Copyleaks/Swift-Plagiarism-Checker.git', :branch => 'master'
  # pod 'PlagiarismChecker', :path => '../'

  target 'PlagiarismChecker_Tests' do
    inherit! :search_paths

    
  end
end
